domain: example.com
url: https://example.com
baseurl: "/Vrush Stuff"

title: Vrush Stuff
email: turning20w@gmail.com
author: Vrush

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  email: "turning20w@gmail.com"
  telegram: "https://t.me/"
  discord: "https://discord.com/"
